### ISSUE TITLE
Can not see any Examples

### ISSUE THREAD

**Issue by chervyakovru** [gravity-ui/yagr#52]
Hello! It is what i see when open the link https://yagr.tech/en/examples/scale-transformations

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/14909082/223490649-112ee1d7-21c5-4739-be13-f41e38ae83c7.png">

**Comment by zefirka** [comment]
<img width="1840" alt="Screenshot 2023-04-12 at 02 25 31" src="https://user-images.githubusercontent.com/5380542/231302282-580bc1e8-fb61-4f75-a792-f6cbbf5c7f6e.png">

Possibly jsfiddle is blocked by you isp? I checked from different browsers and it's ok for me.

**Comment by chervyakovru** [comment]
> Possibly jsfiddle is blocked by you isp? I checked from different browsers and it's ok for me.

yes, indeed
